version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r3gan-backend
    ports:
      - "8000:8000"
    environment:
      GENERATOR_MODEL_PATH: ./models/R3GAN_ALPHA.pkl
      CLASSIFIER_MODEL_PATH: ./models/CLASSIFIER_ALPHA.pkl
    restart: unless-stopped
